# Generated by Django 4.2.3 on 2023-07-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register1app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='Firstname',
            field=models.CharField(default=1, max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='Lastname',
            field=models.CharField(default=1, max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='mobilenumber',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=25),
        ),
    ]
